### PR TITLE
Make when in adjust optional, add true|false expr.

### PR DESCRIPTION
**Pull request by lukaszachy**
One can ommit when: key to have always passing adjust rule.
Rule can contain 'true' and 'false' as expression.

Solves #154

### CODE REVIEW

**Review by psss — APPROVED** [review]
Looks good. Added just a few minor adjustments in 307e5e4. @lukaszachy are the changes ok?

**Comment by lukaszachy** [comment]
> Looks good. Added just a few minor adjustments in [307e5e4](https://github.com/teemtee/fmf/commit/307e5e4d809e322465d6f13e3cedf79ed9fd15c2). @lukaszachy are the changes ok?

LGTM, Thanks for the adjustements.

**Pull request merged**
