### PR TITLE
Enable the `epel-10` building and testing

### PR DESCRIPTION
**Pull request by lukaszachy**

### CODE REVIEW

**Comment by lukaszachy** [comment]
Missing builddeps, lets try again later.

**Comment by LecrisUT** [comment]
Wouldn't it be EPEL10 where those dependencies will be available?

**Comment by lukaszachy** [comment]
> Wouldn't it be EPEL10 where those dependencies will be available?

Likely, but there isn't any (yet)

**Comment by LecrisUT** [comment]
Sooo, Epel10 target is out ;)

**Comment by psss** [comment]
Also requested a new branch in the `rpms` namespace:

* https://pagure.io/releng/fedora-scm-requests/issue/67761

**Comment by psss** [comment]
The missing dep `python3-filelock` has been already [built](https://koji.fedoraproject.org/koji/buildinfo?buildID=2533233). But it seems we'll have to still wait a bit, until the official repositories are ready.

**Comment by LecrisUT** [comment]
`fc40` builds are being picked up by `epel10` tests?

**Comment by psss** [comment]
@thrix, is this caused by the extra `f40` repositories enabled?

    Error: Transaction test error:
    file /usr/libexec/qemu-bridge-helper conflicts between attempted installs of qemu-kvm-common-18:9.1.0-3.el10.1.x86_64 and qemu-common-2:8.2.2-1.fc40.x86_64
    file /usr/share/man/man7/qemu-block-drivers.7.gz conflicts between attempted installs of qemu-kvm-common-18:9.1.0-3.el10.1.x86_64 and qemu-common-2:8.2.2-1.fc40.x86_64
    file /usr/share/man/man7/qemu-cpu-models.7.gz conflicts between attempted installs of qemu-kvm-common-18:9.1.0-3.el10.1.x86_64 and qemu-common-2:8.2.2-1.fc40.x86_64
    file /usr/share/man/man7/qemu-ga-ref.7.gz conflicts between attempted installs of qemu-kvm-common-18:9.1.0-3.el10.1.x86_64 and qemu-common-2:8.2.2-1.fc40.x86_64
    file /usr/share/man/man7/qemu-qmp-ref.7.gz conflicts between attempted installs of qemu-kvm-common-18:9.1.0-3.el10.1.x86_64 and qemu-common-2:8.2.2-1.fc40.x86_64
    file /usr/share/man/man1/qemu-kvm.1.gz conflicts between attempted installs of qemu-system-x86-core-2:8.2.2-1.fc40.x86_64 and qemu-kvm-common-18:9.1.0-3.el10.1.x86_64

**Comment by psss** [comment]
The smoke plan passed in the `centos-stream-10` job. The rest are failures because `tmt` is not available yet for `el10`.

**Pull request merged**
