### PR TITLE
Release fmf-1.1.0

### PR DESCRIPTION
**Pull request by lukaszachy**
Features and bug fixes:
- Implement a directive for disabling inheritance
- Add support for prepending items during merging
- Explicitly convert context value to string
- Workaround s390x ruamel read issue
- Support reference schemas in validation function
- Add JSON Schema validation method
- Fixes blocking with symbolic link loops
- Use a better way to detect the default git branch
- Add unit tests for comma operator in context rules
- Add examples demonstrating the context syntax

Repo maintenance:
- Create commit builds from the `main` branch
- Enable `epel-9` for copr builds and testing

Trying to follow (where applicable) for tmt release - https://tmt.readthedocs.io/en/stable/contribute.html#release:

Follow the steps below to create a new major or minor release:

- [x]     Use git log --oneline --no-decorate x.y-1.. to generate the changelog
- [x]     Update README with new contributors since the last release
- [x]     Add a Release fmf-x.y.0 commit with the specfile update
- [x]     Create a pull request with the commit, ensure tests pass

Release a new package to Fedora and EPEL repositories:

- [x]     Move the fedora branch to point to the new release
- [x]     Create a source rpm using the make srpm command
- [x]     Enable Fedora kerberos kinit nick@FEDORAPROJECT.ORG
- [x]     Change to the fedora rpms git or fedpkg clone fmf
- [x]     Check out the rawhide branch git checkout rawhide
- [x]     Import the srpm using fedpkg import /path/to/the/srpm
- [x]     Restore any files removed by fedpkg if necessary
- [x]     Ensure the proposed changes are ok and commit them
- [x]     Create a pull request against rawhide from your fork
- [x]     After tests pass, merge the pull request to rawhide
- [x]     Build the package for rawhide fedpkg build --nowait
- [x]     Build package for all [active releases](https://bodhi.fedoraproject.org/releases/) git checkout f33 && git merge rawhide && git push && fedpkg build --nowait
- [x]     Create a bodhi update for each release git checkout f33 && fedpkg update --type enhancement --notes 'Update title'

Finally, if everything went well:

- [ ]     Manually merge the original release pull request on github (to avoid rebase) git checkout main && git merge --ff-only <release_branch> && git push origin main
- [x]     Tag the commit with x.y.0, push tags git push --tags
- [ ]     Create a new github release based on the tag above
- [ ]     If the automation triggered by publishing the new github release was not successful, publish the fresh code to the [pypi](https://pypi.org/project/tmt/) repository manually using make wheel && make upload
- [ ]     Once the [copr build](https://copr.fedorainfracloud.org/coprs/psss/tmt/builds/) is completed, move the quay branch to point to the release commit as well to build fresh container images.
- [ ]     Close the corresponding release milestone

### CODE REVIEW

**Comment by lukaszachy** [comment]
https://src.fedoraproject.org/rpms/fmf/pull-request/7

**Comment by lukaszachy** [comment]
Karma call: https://bodhi.fedoraproject.org/updates/?packages=fmf

**Comment by lukaszachy** [comment]
@psss I don't have PyPI credentials, we should add "autorelease" github action - in the mean time could you submit new PyPI version?

**Comment by psss** [comment]
Adding in #174, let's see if it works.

**Pull request merged**
